## numpy

In [1]:
import numpy as np

Q.1.1  
★ 1,2,3,4の配列を作れ

In [3]:
import numpy as np

arrary_1 = np.array([1,2,3,4])

arrary_1

array([1, 2, 3, 4])

Q.1.2  
★以下の２次元配列を作れ  
1,2,4  
8,16,32

In [5]:
arrary_1 = np.array([[1,2,3,4], [8, 16, 32]])

arrary_1

array([list([1, 2, 3, 4]), list([8, 16, 32])], dtype=object)

Q.1.3  
★1,2,3,4,5,6の配列を作り、2行3列に変換せよ

In [6]:
lis = np.array([1,2,3,4,5,6])

array_1 = np.array(lis).reshape(2,3)

array_1

array([[1, 2, 3],
       [4, 5, 6]])

Q.1.4  
★1,2,3,4,5,6の配列を作り、6行1列に変換せよ

In [9]:
lis = np.array([1,2,3,4,5,6])

array_1 = np.array(lis).reshape(6,1)

array_1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Q.1.5  
★以下の２次元配列を作り、1次元配列に変換せよ  
1,2,4  
8,16,32

In [10]:
lis = np.array([[1,2,4], [8,16,32]])
array = lis.flatten()
print(array)

[ 1  2  4  8 16 32]


Q.1.6  
★以下の２次元配列を作り、何行何列か調べよ  
1,2,4  
8,16,32

Q.1.7  
★以下の２次元配列を作り、次元数を調べよ  
1,2,4  
8,16,32

In [11]:
lis = np.array([[1,2,4], [8,16,32]])
lis.shape

(2, 3)

Q.1.8  
★以下の２次元配列を作り、要素数を調べよ  
1,2,4  
8,16,32

Q.2.1  
★1-100までの配列を作成せよ

In [2]:
import numpy as np
array = np.arange(1,101,1)

array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

Q.2.2  
★以下の２次元配列を作れ  
0,0,0,0,0  
0,0,0,0,0

In [11]:
array = np.zeros((2,5))

array = np.zeros((2,5))
print(array)  

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Q.2.3  
★3行4列の0-1の乱数の配列を作れ

In [12]:
array = np.random.rand(3, 4)
print(array)

[[0.23394062 0.97341312 0.31270821 0.74396788]
 [0.92578752 0.74351263 0.02028723 0.79548726]
 [0.96810317 0.26898337 0.04722327 0.55365859]]


Q.3.1  
★1,2,4の配列と8,16,32の配列を作り、2つの配列を結合し1,2,4,8,16,32の配列を作れ

In [3]:
array = np.array([[1,2,4], [8, 16, 32]])
array = array.flatten()
array

array([ 1,  2,  4,  8, 16, 32])

Q.3.2  
★以下の２次元配列を作り、2行1列の要素を切り出せ  
1,2,3  
4,5,6  
7,8,9

In [18]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array)

print(array[1, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
4


Q.3.3    
★以下の２次元配列を作り、最終行最終列の要素を切り出せ  
1,2,3  
4,5,6  
7,8,9

In [4]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array)
print(array[-1, -1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


Q.3.4    
★以下の２次元配列を作り、1行目の要素を切り出せ  
1,2,3  
4,5,6  
7,8,9

In [8]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array[0, :])

[1 2 3]


Q.3.5    
★以下の２次元配列を作り、3行1-2列の要素を切り出せ  
1,2,3  
4,5,6  
7,8,9

Q.4.1  
★ 以下の計算をせよ（ブロードキャストを利用しても良い）  

$\displaystyle \left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) + \left(\begin{array}{ccc} 1 & 1 & 1\\ 1 & 1 & 1 \\ \end{array}\right)$

In [20]:
np.arange(1, 7).reshape(2, 3) + 1

array([[2, 3, 4],
       [5, 6, 7]])

Q.4.2  
★ 以下の計算をせよ（ブロードキャストを利用しても良い）  

$\displaystyle \left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) - \left(\begin{array}{ccc} 1 & 2 & 3\\ 1 & 2 & 3 \\ \end{array}\right)$

In [22]:
np.arange(1, 7).reshape(2, 3) - np.array([[1,2,3],[1,2,3]])

array([[0, 0, 0],
       [3, 3, 3]])

Q.4.3  
★ 以下の計算をせよ（ブロードキャストを利用しても良い）  

$\displaystyle 3\left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) - 2\left(\begin{array}{ccc} 1 & 2 & 3\\ 1 & 2 & 3 \\ \end{array}\right)$

In [23]:
3 * np.arange(1, 7).reshape(2,3) - 2* np.arange(1, 4).reshape(1, 3)

array([[ 1,  2,  3],
       [10, 11, 12]])

In [10]:
np.arange(1, 4).reshape(1, 3)

array([[1, 2, 3]])

In [26]:
3*np.arange(1,7).reshape(2,3) - 2*np.arange(1,4).reshape(1,3)

array([[ 1,  2,  3],
       [10, 11, 12]])

Q.4.4  
★ 以下の内積を計算せよ  

$\displaystyle \left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) \left(\begin{array}{ccc} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{array}\right)$

In [7]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 7).reshape(3, 2)

np.dot(A, B)

array([[22, 28],
       [49, 64]])

Q.5.1  
★ 以下の2次元配列をそれぞれ行方向と列方向に合計した１次元配列を求めよ 

$\displaystyle \left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right)$

In [30]:
array = np.arange(1,7).reshape(2,3)
print(np.sum(array, axis=0))

[5 7 9]


Q.6.1  
★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（シグモイド関数）  
$\displaystyle{f(x)=\frac{1}{(1+\exp(-x))}}$

In [3]:
# ヒント  
array = np.array([0,1,2])
print(np.exp(array))


[1.         2.71828183 7.3890561 ]


In [34]:
array = np.array([0,1,2])
array = 1/(1+np.exp(array)*-1)
array

/Users/seijisuzuki/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([        inf, -0.58197671, -0.15651764])

Q.6.2  
★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ステップ関数）  
$f(x)=1  (x>0)$  
$f(x)=0  (x\le0)$

In [ ]:
# ヒント
array = np.array([-1,0,1,2])
print(array > 0)
print(np.array([True, False]).astype(int))

Q.6.3  
★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ReLU関数）  
$f(x)=x  (x>0)$  
$f(x)=0  (x\le0)$

In [ ]:
# ヒント
array = np.array([-1,0,1,2])
print(np.maximum(1, array))

Q.6.4  
★★1次元の引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ソフトマックス関数）  
$\displaystyle f(x_k)=\frac{\exp(x_k)}{\sum_{i=1}^{n}\exp(x_i)}$  


In [ ]:
# ヒント
array = np.array([1,2,3])
np.sum(array)

Q.6.5  
★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ソフトマックス関数）  
$\displaystyle f(x_k)=\frac{\exp(x_k)}{\sum_{i=1}^{n}\exp(x_i)}$  


In [ ]:
# ヒント
array = np.array([[1,2,3],[4,5,6]])
np.sum(array, axis=1)

Q.6.6  
★★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ソフトマックス関数）  
$\displaystyle f(x_k)=\frac{\exp(x_k)}{\sum_{i=1}^{n}\exp(x_i)}$  
ただし、要素が大きいと上記数式のソフトマックス関数はオーバーフローしてしまう。  
配列から配列の最大値を引くオーバーフロー対策をせよ。

Q.7.1  
★★まとめ問題  
文章の単語の共起行列からコサイン類似度を求めたい  
参考：https://public-constructor.com/co-occurence-matrix-and-vector-cosine-similarity/  
以下の数式を参考に、ベクトルを2つ引数で取り、コサイン類似度を求めるget_cos_similarity関数を実装せよ。  

<コサイン類似度>  
$\displaystyle \overrightarrow{a}=(a_1,a_2,\cdots,a_n)$,$\overrightarrow{b}=(b_1,b_2,\cdots,b_n)$の時、  

$\displaystyle \dfrac{a_1b_1+\cdots +a_nb_n}{\sqrt{a_1^2+\cdots +a_n^2}\sqrt{b_1^2+\cdots +b_n^2}}$


また、以下の設計図とjupyterのコードを参考にして、コサイン類似度を求めるクラスを作成せよ  

In [ ]:
# ヒント  
print("abc".replace("b", "z")) # replaceで置き換えることができる　　
print()
print("a,b,c".split(",")) # splitで分割したリストを作成することができる  
print()

array = np.array([1,2,3])
print(np.sqrt(array)) # ルートを計算できる　　
print()
print(array**2) # 二乗を計算できる

In [ ]:
# 設計図  
#class CoOccurrenceMatrix:
    
    # ＜コンストラクタ＞
    # 文章を引数として受け取り、共起行列を作成してインスタンス変数に保存する
    
    #＜メソッド＞
    #  2つの単語を引数としてとり、コサイン類似度を計算して返却する    

In [ ]:
# 以下、jupyterコード

In [ ]:
text = "If you can dream it, you can do it."

In [ ]:
# 文章の前処理
words = text.lower().replace(".", " .").replace(",", " ,").split(" ")
print(words)

In [ ]:
# コーパスの作成
word_to_id = {}
id_to_word = {}
corpus = []
for word in words:
    if word not in word_to_id:
        idx = len(word_to_id)
        word_to_id[word] = idx
        id_to_word[idx] = word
        
    corpus.append(word_to_id[word])

print(word_to_id)
print(id_to_word)
print(corpus)

In [ ]:
# 共起行列を作成
word_size = len(set(corpus))
matrix = np.zeros((word_size, word_size))

for idx, word_id in enumerate(corpus):
    
    left_idx = idx - 1
    right_idx = idx + 1
    
    if left_idx >= 0:
        left_word_id = corpus[left_idx]
        matrix[word_id, left_word_id] += 1

    if right_idx < len(corpus):
        right_word_id = corpus[right_idx]
        matrix[word_id, right_word_id] += 1

print(matrix)

In [ ]:
# 詳細に確認
header = ""
detail = ""
for idx, row in enumerate(matrix):
    header = header + id_to_word[idx] + " "
    detail = detail + "{}\n{}\n".format(id_to_word[idx], row) 

print(words)
print()
print(header)
print()
print(detail)    

In [ ]:
def get_cos_similarity(a, b):
    ### ここに実装せよ
    

In [ ]:
# コサイン類似度を求める
vec_a = matrix[word_to_id["you"]]
vec_b = matrix[word_to_id["it"]]

get_cos_similarity(vec_a, vec_b)

In [ ]:
### 以下にクラスを書け