# Python入門修了試験

- ファイル名の[氏名]を修正してください。**その際、[ ]は残してください。**
- Q.01-16の問題は関数のコードを修正して回答する形となっています。  
- 機械的に採点を行うので **関数名を変更しないでください。**
- 確認のためのコードを残しておいても構いませんが、なるべく**エラーが出るコードは残しておかないでください。**
- 試験終了後、ファイルを保存し、指示に従って提出してください。

例題  
引数：1つ  
処理：引数に1を加えて返却する

In [1]:
def q00(x):
    
    # 関数名は変えずに引数や処理内容、返却値を修正する形で回答します。

    ret = x + 1
    
    return ret

Q.01  
引数：２つ  
処理：合計して返却する

In [2]:
def q01(x, y):

    return x+y

Q.02    
引数：1つ  
処理：引数が100以上の場合に100と、それ未満の場合は引数の値を返却する

In [ ]:
def q02(x):
    if x >= 100:
        return 100
    else:
        return x


Q.03    
引数：なし  
処理：[1,2,3, ... ,99,100]　（1から100までのリスト）を作成して返却する

In [3]:
def q03():
    lis = list(range(1, 101))
    
    return lis

Q.04    
引数：１つ  
処理：引数にタプルを与えると全ての要素を３倍したリストを返却する  
例：(1,2,3)→[3,6,9]

In [ ]:
def q04(tup):

    return list(tup)

Q.05    
引数：１つ  
処理：引数にリストを与えると降順に並べ替えたリストを返却する    
例：[1,3,2]→[3,2,1]

In [ ]:
def q05(lis):

    return     lis.sort(revers = True)

Q.06    
引数：2つ  
処理：引数にkeyとvalueのリストを与えるとディクトを作成して返却する  
例：["A","B","C"],[1,2,3]→{"A":1,"B":2,"C":3}

In [ ]:
def q06(key, value):
    for x, y in key, value:
        dic = {key, value}
    
    return dic

Q.07    
引数：なし  
処理：ゼロを返却するget_zeroというメソッドを持つクラスGetZero（インスタンスではない）を返却する    

In [ ]:
def q07():
    
    # ヒント
    class GetZero:
        pass
    
    return GetZero

Q.08    
引数：なし  
処理：以下のnumpyの２次元配列を返却する   
1,2,4  
8,16,32

In [6]:
import numpy as np
def q08():
    array = np.array([[1,2,4], [8,16,32]])
    
    return array
                      
q08()

array([[ 1,  2, 34],
       [ 8, 16, 32]])

Q.09    
引数：１つ  
処理：引数にnumpyの２次元配列を与えると、1列目の要素を配列として返却する   
例：  
1,2,4  
8,16,32  
↓  
1,8

In [43]:
def q09(array):

    
    return array[0, :]

array = np.array([[1,2,4], [8,16,32]])

q09(array)

array([1, 2, 4])

Q.10    
引数：なし  
処理：以下の計算結果をnumpyの配列で返却する   
$\displaystyle 3\left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) - 2\left(\begin{array}{ccc} 1 & 2 & 3\\ 1 & 2 & 3 \\ \end{array}\right)$

In [12]:
def q10():
    array1 = np.arange(1,7).reshape(2,3)
    array2 = np.array([[1,2,3]])
    
    return 3*array1 -2*array2

q10()

array([[ 1,  2,  3],
       [10, 11, 12]])

Q.11    
引数：１つ  
処理：引数にnumpyの２次元配列を与えると、列方向に合計した配列を返却する   
例：  
1,2,4  
8,16,32  
↓  
7,56

In [13]:
def q11(array):
    array = np.array.sum(axis=0)
    
    return

### 以降の問題でdfという変数は、下記のデータフレームのことを指します。

In [14]:
import numpy as np
import pandas as pd
df = pd.DataFrame(data=[[1,2,3],
                                              [4,5,6],
                                              [np.nan, 8, 9],
                                              [np.nan, 11, 12],
                                              [13, np.nan, 15],
                                              [16, 17, 18]], columns=["A", "B", "C"])

Q.12    
引数：１つ  
処理：引数にdfを与えると、最終行最終列の値を返却する。

In [18]:
def q12(df):
    array = np.array(df)
    
    return array[-1, -1]

q12(df)

18.0

Q.13    
引数：１つ  
処理：引数にdfを与えると、(行数, 列数)のタプルを返却する。   

In [19]:
def q13(df):
    t = tuple(df)
    return t

q13(df)

('A', 'B', 'C')

Q.14    
引数：１つ  
処理：引数にdfを与えると、B列を除いたA,C列のみのデータフレームを返却する。

In [29]:
def q14(df):
    array = np.array(df)
    
    return array.delete["B"]

#q14(df)
df.info

<bound method DataFrame.info of       A     B   C
0   1.0   2.0   3
1   4.0   5.0   6
2   NaN   8.0   9
3   NaN  11.0  12
4  13.0   NaN  15
5  16.0  17.0  18>

Q.15    
引数：１つ  
処理：引数にdfを与えると、欠損値を全て0埋めしたデータフレームを返却する。

In [49]:
def q15(df):
    
    return df.fillinzero()


q15(df)


AttributeError: 'DataFrame' object has no attribute 'fillinzero'

Q.16    
引数：１つ  
処理：引数にdfを与えると、C列という列名をDという列名に変更したデータフレームを返却する。

In [ ]:
def q16(df):
    
    return

### 以降の問題はグラフを表示する問題になります。 部分点があるので少しでも指示に近いをグラフを描いてください。

Q.17    
以下を折れ線グラフで表示せよ。  
- yの値：[1, 2, 1, 2, 1]  
- グリッド線：あり
- タイトル名：title

In [ ]:
# write answer here


Q.18    
以下を棒グラフで表示せよ。  
- yの値：[1, 2, 1, 2, 1]
- xのティックラベル：["A","B","C","D","E"]
- xラベル名：label_x
- yラベル名：label_y

In [ ]:
# write answer here


Q.19    
以下を散布図で表示せよ。  
- xの値：[1, 2, 3, 4, 5]
- yの値：[1, 2, 1, 2, 1]
- マーカー：x
- 色：赤

In [ ]:
# write answer here


Q.20    
以下をヒストグラムで表示せよ。  
- データの値：[1,2,4,8,16,32,64]
- ヒストグラムの棒の数：10
- 凡例：histgram
- 凡例の位置：真ん中上

In [ ]:
# write answer here


#### 問題は以上になります。お疲れ様でした。